import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import ClientLayout from "./ClientLayout";
import NavigationClient from "@/components/common/header/NavigationClient";
import FooterClient from "@/components/common/footer/FooterClient";
import { ErrorBoundary } from "@/components/errorBoundary/ErrorBoundary";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          {/* <ClientLayout> */}
            <NavigationClient/>
            {/* <ErrorBoundary> */}
            {children}
            {/* </ErrorBoundary> */}
            <FooterClient/>
          {/* </ClientLayout> */}
          <Toaster/>
        </ReduxProvider>
      </body>
    </html>
  );
}
